---
- hosts: all
  name: Configures Nginx
  gather_facts: false
  become: true
  become_method: sudo
  vars:
    server_name: 'maximullaris.com'
    document_root: '/var/www/maximullaris.com'
#    app_root: html_demo_site-main
  tasks:
    - name: Create site folder if doesn't exist
      file:
        path: "{{ document_root }}"
        state: directory
        mode: '0755'

    - name: Copy website files to the server's document root
      copy:
        src: "web/index.html"
        dest: "{{ document_root }}/"
#        mode: preserve
        mode: '0755'

    - name: Apply Nginx template
      template:
        src: web/nginx-www.conf.j2
        dest: /etc/nginx/sites-available/www
      notify: Restart Nginx

    - name: Disable default site
      file:
        path: /etc/nginx/sites-available/default
        state: absent
      notify: Restart Nginx

    - name: Enable new site
      file:
        src: /etc/nginx/sites-available/www
        dest: /etc/nginx/sites-enabled/www
        state: link
      notify: Restart Nginx

#    - name: Allow all access to tcp port 80
#      ufw:
#        rule: allow
#        port: '80'
#        proto: tcp

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
